preprocessing:
  acc_smoothing_window: 10

step_detection:
  height: 12.0
  distance_s: 0.35
  prominence: 0.4

heading:
  gyro_axis: "z"
  gyro_sign: -1.0
  gyro_sign_overrides:
    hand_002_turnright: 1.0
  initial_heading_rad: 0.0
  use_bias_correction: true
  bias_static_duration_s: 2.0

pdr:
  step_length_m: 0.65

visualization:
  figure_dpi: 200
  equal_axis: true
  show_grid: true
